version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: magento-web
    volumes:
      - ./magento:/var/www/html:cached,z
      - ./magento/app:/var/www/html/app:delegated,z
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - db
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: magento-php
    expose:
      - '9000'
    volumes:
      - ./magento:/var/www/html:cached,z
      - ./magento/app:/var/www/html/app:delegated,z
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: magento-db
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql:cached,z
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'magento'
      MYSQL_USER: 'magento'
      MYSQL_PASSWORD: 'magento'

volumes:
  database:
