version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: magento-web
    volumes:
      - ./magento:/app:delegated
      - vendor-files:/app/vendor
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: magento-php
    volumes:
      - ./magento:/app:delegated
      - vendor-files:/app/vendor
    depends_on:
      - db
  db:
    image: mariadb:10.4
    container_name: magento-db
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql:cached,z
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'magento'
      MYSQL_USER: 'magento'
      MYSQL_PASSWORD: 'magento'
  es:
    image: elasticsearch:7.9.0
    container_name: magento-es
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node

volumes:
  vendor-files:
  database:
